// TODO add partial client configs
// split to auth and unauth endpoints

export const URLS = [
    '/en/api/clientconfig',
    '/health/dsl',
    '/health/config',
    '/en/api/clientconfig/partial?configNames=vnHeader&configNames=vnCssOverrides',
    '/bg/api/clientconfig/partial?configNames=vnHeader&configNames=vnCssOverrides',
    '/fr/api/clientconfig/partial?configNames=vnHeader&configNames=vnCssOverrides',
    '/de-at/api/clientconfig/partial?configNames=vnHeader&configNames=vnCssOverrides',
    '/es/api/clientconfig/partial?configNames=vnHeader&configNames=vnCssOverrides',
    '/hu/api/clientconfig/partial?configNames=vnHeader&configNames=vnCssOverrides',
    '/pl/api/clientconfig/partial?configNames=vnHeader&configNames=vnCssOverrides',
    '/bg/api/contentMessages',
    '/en/api/contentMessages',
    '/fr/api/contentMessages',
    '/es/api/contentMessages',
    '/de-at/api/contentMessages',
    '/en/api/asyncdsl/list',
    '/pl/api/contentMessages',
    '/hu/api/contentMessages',
    '/bg/api/asyncdsl/list',
    '/fr/api/asyncdsl/list',
    '/en/api/asyncdsl/group',
    '/en/sports/en/api/clientconfig',
    '/es/api/asyncdsl/list',
    '/de-at/api/asyncdsl/list',
    '/bg/api/asyncdsl/group',
    '/bg/api/clientconfig',
    '/bg/api/content',
    '/en/api/content',
    '/fr/api/asyncdsl/group',
    '/fr/api/clientconfig',
    '/fr/api/content',
    '/pl/api/asyncdsl/list',
    '/hu/api/asyncdsl/list',
    '/en/api/offers/count',
    '/de-at/api/asyncdsl/group',
    '/es/api/asyncdsl/group',
    '/es/api/clientconfig',
    '/de-at/api/clientconfig',
    '/es/api/content',
    '/de-at/api/content',
    '/pl/api/asyncdsl/group',
    '/es-xl/api/clientconfig/partial?configNames=vnHeader&configNames=vnCssOverrides',
    '/pl/api/clientconfig',
    '/pl/api/content',
    '/hu/api/asyncdsl/group',
    '/hu/api/clientconfig',
    '/hu/api/content',
    '/en/api/balance',
    '/en/api/kycstatus',
    '/en/api/balance/bonus',
    '/bg/api/smartbanner',
    '/en/api/playerlimits',
    '/en/api/auth/sessiontimeleft',
    '/en/api/inbox/count',
    '/en/api/smartbanner',
    '/en/api/tourneytokenbalance',
    '/en/api/userflags',
    '/en/api/userdocuments',
    '/fr/api/smartbanner',
    '/es-xl/api/contentMessages',
    '/en/api/sofstatusdetails',
    '/en/api/affordability/snapshotdetails',
    '/en/api/recaptcha/enabled',
    '/en/api/login',
    '/en/api/communicationsettings',
    '/es-xl/api/asyncdsl/list',
    '/de-at/api/smartbanner',
    '/pl/api/smartbanner',
    '/en/api/gamingdeclaration',
    '/es-xl/api/asyncdsl/group',
    '/en/api/playbreak',
    '/es-xl/api/clientconfig',
    '/es-xl/api/content',
    '/api/auth/rememberme',
    '/en/api/auth/logout',
    '/es/api/smartbanner',
    '/en/api/auth/check',
    '/en/api/bettingstatus',
    '/de-at/api/recaptcha/enabled',
    '/hu/api/smartbanner',
    '/bg/api/recaptcha/enabled',
    '/en/api/offers/promo/1726290',
    '/pl/api/recaptcha/enabled',
    '/api/ping',
    '/es/api/recaptcha/enabled',
    '/fr/api/recaptcha/enabled',
    '/health/_api/serverinfo',
];

const URLS_LAST_INDEX = URLS.length - 1;

export const getUrl = (iteration) => {
    return URLS[URLS_LAST_INDEX === 0 ? 0 : iteration % URLS_LAST_INDEX];
};
