enableStrictSsl: false

httpTimeout: 600000

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJQeElyQXJ1RVNubWc2Z3d3WEVIVWVmbHhMdWJhQ2JXWElYcTllbmJPZURFIn0.eyJzdWIiOiJqZmFjQDAxZ3N0NG1xamdkYncwMDBjamUyMWMwaHZzL3VzZXJzL2IyZCIsInNjcCI6ImFwcGxpZWQtcGVybWlzc2lvbnMvdXNlciIsImF1ZCI6WyJqZnJ0QCoiLCJqZmFjQCoiLCJqZmV2dEAqIiwiamZtZEAqIiwiamZjb25AKiJdLCJpc3MiOiJqZmZlQDAxZ3N0NG1xamdkYncwMDBjamUyMWMwaHZzIiwiaWF0IjoxNjkwODgxNDg5LCJqdGkiOiI3MDkwZDVjOC05MzY3LTQ0YjktYmMzZS00NmQyYmFkMDBmMzkifQ.TDH8uD0xqLW6brr1l622WYq6RuE7--cBQGwwiJooHoEEkT9dUARrA4QtoOFbRDgpcYciVKzhUelPeMGb8XxS4BDXu6t6cfE1jh33IqfOMaxPN6KATcY8VQA4EcRozxrkroZ-QNF-DZrelruwnMlz7oSykLbw9PGrEeoR8OcKyOSsWxUXHW0jqKoPtlzGkuQi2uTOV0soT2YUQ16k5cwoE-dZIHxnENUgAJaa9Y-azrtGuUbAnPLksAceMbt5R3TzYl-KTTtJyKrueI8fgl5wLTco7sDpNKZRiiD9jyqwcitPB7WSaPCKbk8wO1Yy-kX5-7qEMX6EF1qbjCLhM7mrUQ

npmRegistryServer: "https://artifactory.bwinparty.corp/artifactory/api/npm/npm-public"

plugins:
  - checksum: 8f13acff9aef76f5fbfb5474b6d23b14ed3f49258cf4e344229e3515e42f4d6990e3c51b9ab176aa46c407fb9ca97fc0902c6400db5a44e9994d0b53512f3aed
    path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
  - checksum: 5e73a1acbb9741fce1e8335e243c9480ea2107b9b4b65ed7643785ddea9e3019aee254a92a853b1cd71023b16fff5b7d3afd5256fe57cd35a54f8785b8c30281
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://go.mskelton.dev/yarn-outdated/v4"

yarnPath: .yarn/releases/yarn-4.5.1.cjs
