import { InternalVariable } from './internal-variable';

export const varListTypography: InternalVariable[] = [
    //Font family
    {
        name: 'typography/font family/primary',
        type: 'STRING',
        value: 'Roboto',
        category: 'TYPOGRAPHY',
    },
    //Font size
    {
        name: 'typography/font size/y8',
        type: 'FLOAT',
        value: 8,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y9',
        type: 'FLOAT',
        value: 9,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y10',
        type: 'FLOAT',
        value: 10,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y11',
        type: 'FLOAT',
        value: 11,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y12',
        type: 'FLOAT',
        value: 12,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y13',
        type: 'FLOAT',
        value: 13,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y14',
        type: 'FLOAT',
        value: 14,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y15',
        type: 'FLOAT',
        value: 15,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y16',
        type: 'FLOAT',
        value: 16,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y17',
        type: 'FLOAT',
        value: 17,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y18',
        type: 'FLOAT',
        value: 18,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y20',
        type: 'FLOAT',
        value: 20,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y22',
        type: 'FLOAT',
        value: 22,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y24',
        type: 'FLOAT',
        value: 24,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y26',
        type: 'FLOAT',
        value: 26,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y28',
        type: 'FLOAT',
        value: 28,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y30',
        type: 'FLOAT',
        value: 30,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y32',
        type: 'FLOAT',
        value: 32,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y34',
        type: 'FLOAT',
        value: 34,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y36',
        type: 'FLOAT',
        value: 36,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y38',
        type: 'FLOAT',
        value: 38,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y40',
        type: 'FLOAT',
        value: 40,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y42',
        type: 'FLOAT',
        value: 42,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y44',
        type: 'FLOAT',
        value: 44,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y46',
        type: 'FLOAT',
        value: 46,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y48',
        type: 'FLOAT',
        value: 48,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y52',
        type: 'FLOAT',
        value: 52,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y54',
        type: 'FLOAT',
        value: 54,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font size/y56',
        type: 'FLOAT',
        value: 56,
        category: 'TYPOGRAPHY',
    },
    //Line height
    {
        name: 'typography/line height/x3',
        type: 'FLOAT',
        value: 12,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x4',
        type: 'FLOAT',
        value: 16,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x5',
        type: 'FLOAT',
        value: 20,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x6',
        type: 'FLOAT',
        value: 24,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x7',
        type: 'FLOAT',
        value: 26,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x8',
        type: 'FLOAT',
        value: 32,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x9',
        type: 'FLOAT',
        value: 36,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x10',
        type: 'FLOAT',
        value: 40,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x11',
        type: 'FLOAT',
        value: 44,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x12',
        type: 'FLOAT',
        value: 48,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x13',
        type: 'FLOAT',
        value: 52,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x14',
        type: 'FLOAT',
        value: 56,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x15',
        type: 'FLOAT',
        value: 60,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x16',
        type: 'FLOAT',
        value: 64,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x17',
        type: 'FLOAT',
        value: 68,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x18',
        type: 'FLOAT',
        value: 72,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x19',
        type: 'FLOAT',
        value: 76,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/line height/x20',
        type: 'FLOAT',
        value: 80,
        category: 'TYPOGRAPHY',
    },
    // Font weight
    {
        name: 'typography/font weight/x1',
        type: 'FLOAT',
        value: 100,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font weight/x2',
        type: 'FLOAT',
        value: 200,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font weight/x3',
        type: 'FLOAT',
        value: 300,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font weight/x4',
        type: 'FLOAT',
        value: 400,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font weight/x5',
        type: 'FLOAT',
        value: 500,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font weight/x6',
        type: 'FLOAT',
        value: 600,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font weight/x7',
        type: 'FLOAT',
        value: 700,
        // eslint-disable-next-line max-lines
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font weight/x8',
        type: 'FLOAT',
        value: 800,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font weight/x9',
        type: 'FLOAT',
        value: 900,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/font weight/x10',
        type: 'FLOAT',
        value: 1000,
        category: 'TYPOGRAPHY',
    },
    // Paragraph Spacing
    {
        name: 'typography/paragraph spacing/x0',
        type: 'FLOAT',
        value: 0,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x3',
        type: 'FLOAT',
        value: 12,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x4',
        type: 'FLOAT',
        value: 16,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x5',
        type: 'FLOAT',
        value: 20,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x6',
        type: 'FLOAT',
        value: 24,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x7',
        type: 'FLOAT',
        value: 28,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x8',
        type: 'FLOAT',
        value: 32,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x9',
        type: 'FLOAT',
        value: 36,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x10',
        type: 'FLOAT',
        value: 40,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x11',
        type: 'FLOAT',
        value: 44,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x12',
        type: 'FLOAT',
        value: 48,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x13',
        type: 'FLOAT',
        value: 52,
        category: 'TYPOGRAPHY',
    },
    {
        name: 'typography/paragraph spacing/x14',
        type: 'FLOAT',
        value: 56,
        category: 'TYPOGRAPHY',
    },
];
