//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend.Vanilla.ServiceClients.Services.Mail
{
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ServiceFaultType", Namespace = "http://xmlns.bwin.com/types/emailservice/v1")]
    internal class ServiceFaultType : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int ErrorCodeField;

        private string ReasonField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        internal int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        internal string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://xmlns.bwin.com/services/emailservice/v1_0_0", ConfigurationName = "Frontend.Vanilla.ServiceClients.Services.MailService.EmailServicePort")]
    internal interface EmailServicePort
    {

        // CODEGEN: Generating message contract since the operation SendEmail is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.bwin.com/services/emailservice/SendEmailRequest", ReplyAction = "http://xmlns.bwin.com/services/emailservice/SendEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceFaultType), Action = "http://xmlns.bwin.com/services/emailservice/ServiceFault", Name = "ServiceFault", Namespace = "http://xmlns.bwin.com/types/emailservice/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute]
        SendEmailResponse SendEmail(SendEmailRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.bwin.com/types/emailservice/v1")]
    public class SendEmailRequestHeaderType
    {

        private string preferredSmtpFarmField;

        private string[] notificationRecipientsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string PreferredSmtpFarm
        {
            get
            {
                return this.preferredSmtpFarmField;
            }
            set
            {
                this.preferredSmtpFarmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NotificationRecipients", Order = 1)]
        public string[] NotificationRecipients
        {
            get
            {
                return this.notificationRecipientsField;
            }
            set
            {
                this.notificationRecipientsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.bwin.com/types/emailservice/v1")]
    public class SendEmailResponseType
    {

        private string messageIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.bwin.com/types/emailservice/v1")]
    public class AlternateView
    {

        private string contentField;

        private string mediaTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string MediaType
        {
            get
            {
                return this.mediaTypeField;
            }
            set
            {
                this.mediaTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.bwin.com/types/emailservice/v1")]
    public class Attachment
    {

        private string fileNameField;

        private byte[] dataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 1)]
        public byte[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.bwin.com/types/emailservice/v1")]
    public class SendEmailRequestType
    {

        private string messageIdField;

        private string fromField;

        private string[] toField;

        private string replyToField;

        private string[] ccField;

        private string[] bccField;

        private string subjectField;

        private bool isBodyHtmlField;

        private int priorityField;

        private string bodyField;

        private Attachment[] attachmentsField;

        private AlternateView[] alternateViewsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("To", Order = 2)]
        public string[] To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string ReplyTo
        {
            get
            {
                return this.replyToField;
            }
            set
            {
                this.replyToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cc", Order = 4)]
        public string[] Cc
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bcc", Order = 5)]
        public string[] Bcc
        {
            get
            {
                return this.bccField;
            }
            set
            {
                this.bccField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public bool IsBodyHtml
        {
            get
            {
                return this.isBodyHtmlField;
            }
            set
            {
                this.isBodyHtmlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public int Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachments", Order = 10)]
        public Attachment[] Attachments
        {
            get
            {
                return this.attachmentsField;
            }
            set
            {
                this.attachmentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlternateViews", Order = 11)]
        public AlternateView[] AlternateViews
        {
            get
            {
                return this.alternateViewsField;
            }
            set
            {
                this.alternateViewsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    internal class SendEmailRequest
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://xmlns.bwin.com/types/emailservice/v1")]
        public SendEmailRequestHeaderType SendEmailRequestHeader;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.bwin.com/types/emailservice/v1", Order = 0)]
        public SendEmailRequestType SendEmailRequestBody;

        public SendEmailRequest()
        {
        }

        public SendEmailRequest(SendEmailRequestHeaderType SendEmailRequestHeader, SendEmailRequestType SendEmailRequestBody)
        {
            this.SendEmailRequestHeader = SendEmailRequestHeader;
            this.SendEmailRequestBody = SendEmailRequestBody;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    internal class SendEmailResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.bwin.com/types/emailservice/v1", Order = 0)]
        public SendEmailResponseType SendEmailResponseBody;

        public SendEmailResponse()
        {
        }

        public SendEmailResponse(SendEmailResponseType SendEmailResponseBody)
        {
            this.SendEmailResponseBody = SendEmailResponseBody;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal interface EmailServicePortChannel : EmailServicePort, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal class EmailServicePortClient : System.ServiceModel.ClientBase<EmailServicePort>, EmailServicePort
    {

        public EmailServicePortClient()
        {
        }

        public EmailServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendEmailResponse EmailServicePort.SendEmail(SendEmailRequest request)
        {
            return base.Channel.SendEmail(request);
        }

        public SendEmailResponseType SendEmail(SendEmailRequestHeaderType SendEmailRequestHeader, SendEmailRequestType SendEmailRequestBody)
        {
            SendEmailRequest inValue = new SendEmailRequest();
            inValue.SendEmailRequestHeader = SendEmailRequestHeader;
            inValue.SendEmailRequestBody = SendEmailRequestBody;
            SendEmailResponse retVal = ((EmailServicePort)(this)).SendEmail(inValue);
            return retVal.SendEmailResponseBody;
        }
    }
}
