export const staticMapSocial = {
    'color/social/yahoo/base': ['color/social/yahoo/base'],
    'color/social/yahoo/hover': ['color/social/yahoo/light'],
    'color/social/yahoo/active': ['color/social/yahoo/dark'],
    'color/social/on yahoo/base': ['color/neutrals/0'],
    'color/social/yahoo/outline/base': ['color/social/yahoo/base'],
    'color/social/yahoo/outline/hover': ['color/social/yahoo/light'],
    'color/social/yahoo/outline/active': ['color/social/yahoo/dark'],
    'color/social/on yahoo/outline': ['color/neutrals/140'],
    'color/social/paypal/base': ['color/social/paypal/base'],
    'color/social/paypal/hover': ['color/social/paypal/light'],
    'color/social/paypal/active': ['color/social/paypal/dark'],
    'color/social/on paypal/outline': ['color/neutrals/140'],
    'color/social/on paypal/base': ['color/neutrals/0'],
    'color/social/entain/base': ['color/social/entain/base'],
    'color/social/entain/hover': ['color/social/entain/light'],
    'color/social/entain/active': ['color/social/entain/dark'],
    'color/social/on entain/outline': ['color/neutrals/140'],
    'color/social/on entain/base': ['color/neutrals/0'],
    'color/social/on apple/outline': ['color/neutrals/140'],
    'color/social/apple/outline/base': ['color/neutrals/140'],
    'color/social/apple/outline/hover': ['color/neutrals/140'],
    'color/social/apple/outline/active': ['color/neutrals/140'],
    'color/social/on google/outline': ['color/neutrals/140'],
    'color/social/google/outline/base': ['color/neutrals/140'],
    'color/social/google/outline/hover': ['color/neutrals/140'],
    'color/social/google/outline/active': ['color/neutrals/140'],
    'color/social/mlife/base': ['color/social/mlife/base'],
    'color/social/mlife/hover': ['color/social/mlife/light'],
    'color/social/mlife/active': ['color/social/mlife/dark'],
    'color/social/on mlife/outine': ['color/neutrals/140'],
    'color/social/on mlife/base': ['color/neutrals/0'],
    'color/social/facebook/base': ['color/social/facebook/base'],
    'color/social/facebook/hover': ['color/social/facebook/light'],
    'color/social/facebook/active': ['color/social/facebook/dark'],
    'color/social/on facebook/outline': ['color/neutrals/140'],
    'color/social/on facebook/base': ['color/neutrals/0'],
    'color/social/paypal/outline/base': ['color/social/paypal/base'],
    'color/social/paypal/outline/hover': ['color/social/paypal/light'],
    'color/social/paypal/outline/active': ['color/social/paypal/dark'],
    'color/social/entain/outline/base': ['color/social/entain/base'],
    'color/social/entain/outline/hover': ['color/social/entain/light'],
    'color/social/entain/outline/active': ['color/social/entain/dark'],
    'color/social/mlife/outline/base': ['color/social/mlife/base'],
    'color/social/mlife/outline/hover': ['color/social/mlife/light'],
    'color/social/mlife/outline/active': ['color/social/mlife/dark'],
    'color/social/facebook/outline/base': ['color/social/facebook/base'],
    'color/social/facebook/outline/hover': ['color/social/facebook/light'],
    'color/social/facebook/outline/active': ['color/social/facebook/dark'],
    'color/social/apple/base': ['color/neutrals/140'],
    'color/social/apple/hover': ['color/neutrals/140'],
    'color/social/apple/active': ['color/neutrals/140'],
    'color/social/google/base': ['color/neutrals/140'],
    'color/social/google/hover': ['color/neutrals/140'],
    'color/social/google/active': ['color/neutrals/140'],
    'color/social/on apple/base': ['color/neutrals/0'],
    'color/social/on google/base': ['color/neutrals/0'],
};

export const staticMapRadius = {
    'radius/max': ['radius/max'],
    'radius/semi rounded sm': ['radius/x1'],
    'radius/semi rounded md': ['radius/x2'],
    'radius/squared': ['radius/no radius'],
    'radius/semi rounded xs': ['radius/xhalf'],
};

export const staticMapSize = {
    'size/xhalf': ['size/xhalf'],
    'size/x1': ['size/x1'],
    'size/x2': ['size/x2'],
    'size/x3': ['size/x3'],
    'size/x4': ['size/x4'],
    'size/x6': ['size/x6'],
    'size/x8': ['size/x8'],
    'size/x10': ['size/x10'],
    'size/x11': ['size/x11'],
    'size/x12': ['size/x12'],
    'size/x14': ['size/x14'],
    'size/x16': ['size/x16'],
    'size/x18': ['size/x18'],
    'size/x20': ['size/x20'],
    'size/x22': ['size/x22'],
    'size/icon/small': ['size/x3'],
    'size/icon/medium': ['size/x4'],
    'size/icon/large': ['size/x5'],
    'size/icon/xlarge': ['size/x6'],
    'size/x24': ['size/x24'],
    'size/x13': ['size/x13'],
    'size/x25': ['size/x25'],
    'size/x9': ['size/x9'],
    'size/icon/xsmall': ['size/x2'],
    'size/xquarter': ['size/xquarter'],
};

export const staticMapSpacing = {
    'spacing/container/padding 4xl': ['space/x8'],
    'spacing/container/padding 3xl': ['space/x6'],
    'spacing/container/padding 2xl': ['space/x4'],
    'spacing/container/padding xl': ['space/x3'],
    'spacing/container/padding lg': ['space/x2'],
    'spacing/container/padding sm': ['space/x1'],
    'spacing/inline/xl': ['space/x4'],
    'spacing/inline/lg': ['space/x3'],
    'spacing/inline/md': ['space/x2'],
    'spacing/inline/sm': ['space/x1'],
    'spacing/inline/xs': ['space/xhalf'],
    'spacing/stack/xl': ['space/x4'],
    'spacing/stack/lg': ['space/x3'],
    'spacing/stack/md': ['space/x2'],
    'spacing/stack/sm': ['space/x1'],
    'spacing/stack/xs': ['space/xhalf'],
    'spacing/container/padding none': ['space/no space'],
    'spacing/inline/inline none': ['space/no space'],
    'spacing/stack/stack none': ['space/no space'],
    'spacing/stack/2xl': ['space/x5'],
    'spacing/stack/3xl': ['space/x6'],
    'spacing/stack/4xl': ['space/x7'],
    'spacing/stack/5xl': ['space/x8'],
    'spacing/container/padding md': ['space/x1half'],
    'spacing/container/padding xs': ['space/xhalf'],
    'spacing/container/padding 5xl': ['space/x10'],
};

export const staticMapTypography = {
    'typography/display/font family': ['typography/font family/primary'],
    'typography/display/sm/line height': ['typography/line height/x14'],
    'typography/display/sm/font size': ['typography/font size/y40'],
    'typography/display/sm/font weight': ['typography/font weight/x4'],
    'typography/display/sm/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/display/sm strong/line height': ['typography/line height/x14'],
    'typography/display/sm strong/font size': ['typography/font size/y40'],
    'typography/display/sm strong/font weight': ['typography/font weight/x5'],
    'typography/display/sm strong/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/display/md/line height': ['typography/line height/x18'],
    'typography/display/md/font size': ['typography/font size/y48'],
    'typography/display/md/font weight': ['typography/font weight/x4'],
    'typography/display/md/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/display/md strong/line height': ['typography/line height/x18'],
    'typography/display/md strong/font size': ['typography/font size/y48'],
    'typography/display/md strong/font weight': ['typography/font weight/x5'],
    'typography/display/md strong/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/display/lg/line height': ['typography/line height/x20'],
    'typography/display/lg/font size': ['typography/font size/y56'],
    'typography/display/lg/font weight': ['typography/font weight/x5'],
    'typography/display/lg/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/display/lg strong/line height': ['typography/line height/x20'],
    'typography/display/lg strong/font size': ['typography/font size/y56'],
    'typography/display/lg strong/font weight': ['typography/font weight/x7'],
    'typography/display/lg strong/paragraph space': ['typography/paragraph spacing/x0'],

    'typography/headline/font family': ['typography/font family/primary'],
    'typography/headline/sm/line height': ['typography/line height/x9'],
    'typography/headline/sm/font size': ['typography/font size/y24'],
    'typography/headline/sm/font weight': ['typography/font weight/x4'],
    'typography/headline/sm/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/headline/sm strong/line height': ['typography/line height/x9'],
    'typography/headline/sm strong/font size': ['typography/font size/y24'],
    'typography/headline/sm strong/font weight': ['typography/font weight/x5'],
    'typography/headline/sm strong/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/headline/md/line height': ['typography/line height/x10'],
    'typography/headline/md/font size': ['typography/font size/y28'],
    'typography/headline/md/font weight': ['typography/font weight/x4'],
    'typography/headline/md/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/headline/md strong/line height': ['typography/line height/x10'],
    'typography/headline/md strong/font size': ['typography/font size/y28'],
    'typography/headline/md strong/font weight': ['typography/font weight/x7'],
    'typography/headline/md strong/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/headline/lg/line height': ['typography/line height/x13'],
    'typography/headline/lg/font size': ['typography/font size/y36'],
    'typography/headline/lg/font weight': ['typography/font weight/x5'],
    'typography/headline/lg/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/headline/lg strong/line height': ['typography/line height/x13'],
    'typography/headline/lg strong/font size': ['typography/font size/y36'],
    'typography/headline/lg strong/font weight': ['typography/font weight/x7'],
    'typography/headline/lg strong/paragraph space': ['typography/paragraph spacing/x0'],

    'typography/title/font family': ['typography/font family/primary'],
    'typography/title/sm/line height': ['typography/line height/x5'],
    'typography/title/sm/font size': ['typography/font size/y14'],
    'typography/title/sm/font weight': ['typography/font weight/x4'],
    'typography/title/sm/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/title/sm strong/line height': ['typography/line height/x5'],
    'typography/title/sm strong/font size': ['typography/font size/y14'],
    'typography/title/sm strong/font weight': ['typography/font weight/x5'],
    'typography/title/sm strong/paragraph space': ['typography/paragraph spacing/x0'],

    'typography/title/md/line height': ['typography/line height/x6'],
    'typography/title/md/font size': ['typography/font size/y16'],
    'typography/title/md/font weight': ['typography/font weight/x5'],
    'typography/title/md/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/title/md strong/line height': ['typography/line height/x6'],
    'typography/title/md strong/font size': ['typography/font size/y16'],
    'typography/title/md strong/font weight': ['typography/font weight/x7'],
    'typography/title/md strong/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/title/lg/line height': ['typography/line height/x7'],
    'typography/title/lg/font size': ['typography/font size/y20'],
    'typography/title/lg/font weight': ['typography/font weight/x4'],
    'typography/title/lg/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/title/lg strong/line height': ['typography/line height/x7'],
    'typography/title/lg strong/font size': ['typography/font size/y20'],
    'typography/title/lg strong/font weight': ['typography/font weight/x5'],
    'typography/title/lg strong/paragraph space': ['typography/paragraph spacing/x0'],

    'typography/body/font family': ['typography/font family/primary'],
    'typography/body/sm/line height': ['typography/line height/x4'],
    'typography/body/sm/font size': ['typography/font size/y12'],
    'typography/body/sm/font weight': ['typography/font weight/x4'],
    'typography/body/sm/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/body/sm strong/line height': ['typography/line height/x4'],
    'typography/body/sm strong/font size': ['typography/font size/y12'],
    'typography/body/sm strong/font weight': ['typography/font weight/x5'],
    'typography/body/sm strong/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/body/md/line height': ['typography/line height/x5'],
    'typography/body/md/font size': ['typography/font size/y14'],
    'typography/body/md/font weight': ['typography/font weight/x4'],
    'typography/body/md/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/body/md strong/line height': ['typography/line height/x5'],
    'typography/body/md strong/font size': ['typography/font size/y14'],
    'typography/body/md strong/font weight': ['typography/font weight/x5'],
    'typography/body/md strong/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/body/lg/line height': ['typography/line height/x6'],
    'typography/body/lg/font size': ['typography/font size/y16'],
    'typography/body/lg/font weight': ['typography/font weight/x4'],
    'typography/body/lg/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/body/lg strong/line height': ['typography/line height/x6'],
    'typography/body/lg strong/font size': ['typography/font size/y16'],
    'typography/body/lg strong/font weight': ['typography/font weight/x5'],
    'typography/body/lg strong/paragraph space': ['typography/paragraph spacing/x0'],

    'typography/label/font family': ['typography/font family/primary'],
    'typography/label/xs/line height': ['typography/line height/x3'],
    'typography/label/xs/font size': ['typography/font size/y9'],
    'typography/label/xs/font weight': ['typography/font weight/x4'],
    'typography/label/xs/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/label/xs strong/line height': ['typography/line height/x3'],
    'typography/label/xs strong/font size': ['typography/font size/y9'],
    'typography/label/xs strong/font weight': ['typography/font weight/x7'],
    'typography/label/xs strong/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/label/sm/line height': ['typography/line height/x4'],
    'typography/label/sm/font size': ['typography/font size/y11'],
    'typography/label/sm/font weight': ['typography/font weight/x4'],
    'typography/label/sm/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/label/sm strong/line height': ['typography/line height/x4'],
    'typography/label/sm strong/font size': ['typography/font size/y11'],
    'typography/label/sm strong/font weight': ['typography/font weight/x5'],
    'typography/label/sm strong/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/label/md/line height': ['typography/line height/x4'],
    'typography/label/md/font size': ['typography/font size/y12'],
    'typography/label/md/font weight': ['typography/font weight/x4'],
    'typography/label/md/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/label/md strong/line height': ['typography/line height/x4'],
    'typography/label/md strong/font size': ['typography/font size/y12'],
    'typography/label/md strong/font weight': ['typography/font weight/x5'],
    'typography/label/md strong/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/label/lg/line height': ['typography/line height/x4'],
    'typography/label/lg/font size': ['typography/font size/y14'],
    'typography/label/lg/font weight': ['typography/font weight/x4'],
    'typography/label/lg/paragraph space': ['typography/paragraph spacing/x0'],
    'typography/label/lg strong/line height': ['typography/line height/x4'],
    'typography/label/lg strong/font size': ['typography/font size/y14'],
    'typography/label/lg strong/font weight': ['typography/font weight/x5'],
    'typography/label/lg strong/paragraph space': ['typography/paragraph spacing/x0'],
};
