using Frontend.SharedFeatures.Api.Features.DepositSession;
using Frontend.SharedFeatures.Api.Features.TerminalSession;
using Frontend.Vanilla.Core.Configuration;
using Frontend.Vanilla.Features;
using Frontend.Vanilla.Features.AccountUpgrade;
using Frontend.Vanilla.Features.ActivityPopup;
using Frontend.Vanilla.Features.AdobeTarget;
using Frontend.Vanilla.Features.Affordability;
using Frontend.Vanilla.Features.AntiForgeryProtection;
using Frontend.Vanilla.Features.AppInfo;
using Frontend.Vanilla.Features.Badge;
using Frontend.Vanilla.Features.BalanceBreakdown;
using Frontend.Vanilla.Features.BarcodeScanner;
using Frontend.Vanilla.Features.BestationHardwareFault;
using Frontend.Vanilla.Features.BottomNav;
using Frontend.Vanilla.Features.BottomSheet;
using Frontend.Vanilla.Features.Cashier;
using Frontend.Vanilla.Features.Claims;
using Frontend.Vanilla.Features.Clock;
using Frontend.Vanilla.Features.CommonMessages;
using Frontend.Vanilla.Features.ConfirmPassword;
using Frontend.Vanilla.Features.ConfirmPopup;
using Frontend.Vanilla.Features.ContentEndpoint;
using Frontend.Vanilla.Features.ContentMessages;
using Frontend.Vanilla.Features.CookieConsent;
using Frontend.Vanilla.Features.CssOverrides;
using Frontend.Vanilla.Features.CurrentSession;
using Frontend.Vanilla.Features.Date;
using Frontend.Vanilla.Features.DebounceButtons;
using Frontend.Vanilla.Features.DepositLimits;
using Frontend.Vanilla.Features.DepositPrompt;
using Frontend.Vanilla.Features.Device;
using Frontend.Vanilla.Features.Diagnostics.SiteVersion;
using Frontend.Vanilla.Features.DomainSpecificActions;
using Frontend.Vanilla.Features.DomainSpecificLanguage;
using Frontend.Vanilla.Features.DropdownHeader;
using Frontend.Vanilla.Features.DynamicLayout;
using Frontend.Vanilla.Features.EntryWeb.DataLayer;
using Frontend.Vanilla.Features.EntryWeb.Prerender;
using Frontend.Vanilla.Features.FeatureFlags;
using Frontend.Vanilla.Features.Flags;
using Frontend.Vanilla.Features.Footer;
using Frontend.Vanilla.Features.FraudProtection;
using Frontend.Vanilla.Features.Gamification;
using Frontend.Vanilla.Features.HeaderBar;
using Frontend.Vanilla.Features.HomePage;
using Frontend.Vanilla.Features.Icons;
using Frontend.Vanilla.Features.Inactive;
using Frontend.Vanilla.Features.InactivityScreen;
using Frontend.Vanilla.Features.Inbox;
using Frontend.Vanilla.Features.JackpotWinner;
using Frontend.Vanilla.Features.Kyc;
using Frontend.Vanilla.Features.LabelSwitcher;
using Frontend.Vanilla.Features.LanguageSwitcher;
using Frontend.Vanilla.Features.LastKnownProduct;
using Frontend.Vanilla.Features.LastSessionInfo;
using Frontend.Vanilla.Features.LazyFeatures;
using Frontend.Vanilla.Features.LivePerson;
using Frontend.Vanilla.Features.Login.ErrorFormatters;
using Frontend.Vanilla.Features.LoginDuration;
using Frontend.Vanilla.Features.Logout;
using Frontend.Vanilla.Features.LossLimits;
using Frontend.Vanilla.Features.MetaTags;
using Frontend.Vanilla.Features.NativeApp;
using Frontend.Vanilla.Features.NavigationLayout;
using Frontend.Vanilla.Features.Offer;
using Frontend.Vanilla.Features.Offers;
using Frontend.Vanilla.Features.Offline;
using Frontend.Vanilla.Features.OfflinePage;
using Frontend.Vanilla.Features.Page;
using Frontend.Vanilla.Features.PlayBreak;
using Frontend.Vanilla.Features.PlayerActiveWager;
using Frontend.Vanilla.Features.PlayerAttributes;
using Frontend.Vanilla.Features.PlayerGamingDeclaration;
using Frontend.Vanilla.Features.PlayerLimits;
using Frontend.Vanilla.Features.ProductMenu;
using Frontend.Vanilla.Features.Products;
using Frontend.Vanilla.Features.ProductSwitchCoolOff;
using Frontend.Vanilla.Features.ReCaptcha;
using Frontend.Vanilla.Features.RedirectMessage;
using Frontend.Vanilla.Features.ReferredFriends;
using Frontend.Vanilla.Features.RememberMe;
using Frontend.Vanilla.Features.RememberMeLogoutPrompt;
using Frontend.Vanilla.Features.RtmsConnection;
using Frontend.Vanilla.Features.RtmsEvents;
using Frontend.Vanilla.Features.RtmsLayer;
using Frontend.Vanilla.Features.ScreenTime;
using Frontend.Vanilla.Features.SelfExclusion;
using Frontend.Vanilla.Features.SessionInfo;
using Frontend.Vanilla.Features.SessionLimits;
using Frontend.Vanilla.Features.SessionLimitsLogoutPopup;
using Frontend.Vanilla.Features.SingleSignOn;
using Frontend.Vanilla.Features.SmartBanner;
using Frontend.Vanilla.Features.SpeculativeLink;
using Frontend.Vanilla.Features.Tooltips;
using Frontend.Vanilla.Features.TrackerId;
using Frontend.Vanilla.Features.UI;
using Frontend.Vanilla.Features.UrlTransformation;
using Frontend.Vanilla.Features.User;
using Frontend.Vanilla.Features.UserBalance;
using Frontend.Vanilla.Features.UserDocuments;
using Frontend.Vanilla.Features.UserFlags;
using Frontend.Vanilla.Features.UserSummary;
using Frontend.Vanilla.Features.Validation;
using Frontend.Vanilla.Features.ValueSegment;
using Frontend.Vanilla.Features.ValueTicket;
using Microsoft.Extensions.Options;

namespace Frontend.SharedFeatures.Api;

internal static class SharedFeaturesApiServices
{
    /// <summary>
    /// Adds features for SharedFeatures API.
    /// </summary>
    public static IServiceCollection AddSharedFeaturesApiFeatures(this IServiceCollection services)
    {
        // Dependencies
        services.AddVanillaFeatures();

        services.AddSingleton(new DynaConParameter("service", "SFAPI:1"));
        services.AddSingleton(new DynaConParameter("context.product", Constants.Application));
        services.AddSingleton<IDiagnosticsComponentProvider, SharedFeaturesApiDiagnosticsComponentProvider>();
        services.AddSingleton<IConfigureOptions<ContentEndpointOptions>, ContentEndpointBootstrapper>();
        services.AddAffordabilityFeature();
        services.AddAntiForgery();
        services.AddAppInfoFeature();
        services.AddCashierFeatureSfapi();
        services.AddClaimsFeature();
        services.AddContentMessagesFeatureSfapi();
        services.AddDateFeature();
        services.AddDepositSessionFeature();
        services.AddInboxFeature();
        services.AddLastKnownProductFeature();
        services.AddLoginDurationFeature();
        services.AddNativeAppFeature();
        services.AddPageFeature();
        services.AddProductsFeature();
        services.AddKycFeature();
        services.AddGamificationFeature();
        services.AddReCaptchaFeatureSfapi();
        services.AddRememberMeFeature();
        services.AddRememberMeLogoutPromptFeature();
        services.AddRtmsLayerFeature();
        services.AddRtmsEventsFeature();
        services.AddUrlTransformationFeature();
        services.AddUserFeature();
        services.AddUserFlagsFeature();
        services.AddUserDocumentsFeature();
        services.AddLazyFeaturesFeature();
        services.AddSpeculativeLinkFeature();
        services.AddUiFeature();
        services.AddAccountUpgradeFeature();
        services.AddActivityPopupFeature();
        services.AddAdobeTargetFeature();
        services.AddBadgeFeature();
        services.AddBalanceBreakdownFeature();
        services.AddBarcodeScannerFeature();
        services.AddBestationHardwareFaultFeature();
        services.AddBottomNavFeature();
        services.AddBottomSheetFeature();
        services.AddClockFeature();
        services.AddCommonMessagesFeature();
        services.AddConfirmPasswordFeature();
        services.AddConfirmPopupFeature();
        services.AddCookieConsentFeature();
        services.AddCssOverridesFeature();
        services.AddCurrentSessionFeature();
        services.AddDataLayerFeatureSfapi();
        services.AddDebounceButtonsFeature();
        services.AddDepositLimitsFeature();
        services.AddDepositPromptFeature();
        services.AddDeviceFeature();
        services.AddDomainSpecificActionsFeatureSfapi();
        services.AddDomainSpecificLanguageFeature();
        services.AddDropdownHeaderFeature();
        services.AddDynamicLayoutFeature();
        services.AddFeatureFlagsFeature();
        services.AddPrerenderFeatureSfapi();
        services.AddFlagsFeature();
        services.AddFooterFeature();
        services.AddFraudProtectionFeature();
        services.AddHeaderBarFeature();
        services.AddHomePageFeature();
        services.AddIconsFeature();
        services.AddInactiveFeature();
        services.AddInactivityScreenFeature();
        services.AddLabelSwitcherFeature();
        services.AddLanguageSwitcherFeature();
        services.AddLastSessionInfoFeature();
        services.AddLaunchDarklyFeature();
        services.AddLivePersonFeature();
        services.AddLoginErrorConvertersFeature();
        services.AddLogoutFeature();
        services.AddLossLimitsFeature();
        services.AddMetaTagsFeature();
        services.AddNavigationLayoutFeature();
        services.AddOfferFeature();
        services.AddOffersFeature();
        services.AddOfflinePageFeature();
        services.AddPlayBreakFeature();
        services.AddPlayerGamingDeclarationFeature();
        services.AddPlayerActiveWagerFeature();
        services.AddPlayerAttributesFeature();
        services.AddJackpotWinnerFeature();
        services.AddPlayerLimitsFeature();
        services.AddProductMenuFeature();
        services.AddProductSwitchCoolOffFeature();
        services.AddPwaFeature();
        services.AddRedirectMessageFeature();
        services.AddReferredFriendsFeature();
        services.AddRtmsConnectionFeature();
        services.AddScreenTimeFeature();
        services.AddSelfExclusionFeature();
        services.AddSessionInfoFeature();
        services.AddSessionLimitsFeature();
        services.AddSessionLimitsLogoutPopupFeature();
        services.AddSingleSignOnFeature();
        services.AddSmartBannerFeature();
        services.AddTerminalSessionFeature();
        services.AddTooltipFeature();
        services.AddTrackerIdFeatureSfapi();
        services.AddUserBalanceFeature();
        services.AddUserSummaryFeature();
        services.AddValidationFeature();
        services.AddValueTicketFeature();
        services.AddValueSegmentFeature();

        return services;
    }
}
