import { Theme } from './themes.types';

export const THEME_LIST: Theme[] = [
    {
        exportedFigmaName: 'betboo-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-betboo',
        name: 'Betboo-light',
    },
    {
        exportedFigmaName: 'betboo-brazil-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-betboo-br',
        name: 'Betboo-brazil',
    },
    {
        exportedFigmaName: 'betmgm-hybrid',
        enableDarkBg: false,
        mainThemeparkClass: 'th-mgm-4',
        alternativeThemeparkClasses: ['th-mgm-3', 'th-mgm-2'],
        name: 'BetMGM-hybrid',
    },
    {
        exportedFigmaName: 'borgata-hybrid',
        enableDarkBg: false,
        mainThemeparkClass: 'th-borgata-sports-2',
        alternativeThemeparkClasses: ['th-borgata-2', 'th-borgata-casino-2', 'th-borgata-poker-2', 'th-borgata-bingo'],
        name: 'Borgata-hybrid',
    },
    {
        exportedFigmaName: 'bwin-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-bwin',
        alternativeThemeparkClasses: ['th-black'],
        name: 'Bwin-light',
    },
    {
        exportedFigmaName: 'bwin-dark',
        enableDarkBg: true,
        mainThemeparkClass: 'th-bwin-dark',
        alternativeThemeparkClasses: ['th-black-dark'],
        name: 'Bwin-dark',
    },
    {
        exportedFigmaName: 'coral-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-coral',
        name: 'Coral',
    },
    {
        exportedFigmaName: 'danskespil-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-danske-spil',
        name: 'Danskespil',
    },
    {
        exportedFigmaName: 'danskespilpoker-dark',
        enableDarkBg: true,
        mainThemeparkClass: 'th-danske-poker',
        name: 'Danskespilpoker',
    },
    {
        exportedFigmaName: 'foxybingo-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-foxy-bingo-5',
        alternativeThemeparkClasses: ['th-foxy-bingo-4'],
        name: 'Foxy-bingo',
    },
    {
        exportedFigmaName: 'foxygames-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-foxy-games-3',
        alternativeThemeparkClasses: ['th-foxy-games-2'],
        name: 'Foxy-games',
    },
    {
        exportedFigmaName: 'galabingo-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-gala-bingo-3',
        name: 'Galabingo',
    },
    {
        exportedFigmaName: 'galacasino-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-gala-casino-2',
        name: 'Galacasino',
    },
    {
        exportedFigmaName: 'gamebookers-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-gamebookers',
        name: 'Gamebookers',
    },
    {
        exportedFigmaName: 'giocodigitale-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-giocodigitale',
        name: 'GiocoDigitale',
    },
    {
        exportedFigmaName: 'ladbrokes-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-ladbrokes',
        name: 'Ladbrokes',
    },
    {
        exportedFigmaName: 'ladbrokes-germany-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-ladbrokes-de',
        name: 'Ladbrokes-germany',
    },
    {
        exportedFigmaName: 'ninjacasino-dark',
        enableDarkBg: true,
        mainThemeparkClass: 'th-ninja-casino',
        name: 'Ninjacasino',
    },
    {
        exportedFigmaName: 'oddset-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-oddset',
        name: 'Oddset',
    },
    {
        exportedFigmaName: 'optibet-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-optibet',
        name: 'Optibet',
    },
    {
        exportedFigmaName: 'partycasino-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-party-casino',
        name: 'PartyCasino',
    },
    {
        exportedFigmaName: 'partycasino-2-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-party-casino-2',
        name: 'Partycasino-2 (OneParty)',
    },
    {
        // This should not be a theme, as it is equal to partycasino
        exportedFigmaName: 'partyslots-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-party-casino',
        name: 'PartySlots (Germany)',
    },
    {
        exportedFigmaName: 'partypoker-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-party-poker',
        name: 'PartyPoker',
    },
    {
        exportedFigmaName: 'partypoker-2-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-party-poker-2',
        name: 'Partypoker-2 (OneParty)',
    },
    {
        exportedFigmaName: 'partysports-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-party-sports-2',
        alternativeThemeparkClasses: ['th-party-sports'],
        name: 'PartySports (OneParty)',
    },
    {
        exportedFigmaName: 'pmu-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-pmu-2',
        alternativeThemeparkClasses: ['th-pmu'],
        name: 'Pmu',
    },
    {
        exportedFigmaName: 'premium-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-premium',
        name: 'Premium-light',
    },
    {
        exportedFigmaName: 'premium-dark',
        enableDarkBg: true,
        mainThemeparkClass: 'th-premium-dark',
        name: 'Premium-dark',
    },
    {
        exportedFigmaName: 'slotclub-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-slotclub',
        name: 'Slotclub',
    },
    {
        exportedFigmaName: 'sportingbet-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-sportingbet-2',
        alternativeThemeparkClasses: ['th-sportingbet'],
        name: 'Sportingbet',
    },
    {
        exportedFigmaName: 'sportingbet-brazil-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-sportingbet-br',
        name: 'Sportingbet-brazil',
    },
    {
        exportedFigmaName: 'sportsinteraction-dark',
        enableDarkBg: true,
        mainThemeparkClass: 'th-sports-interaction',
        name: 'Sportsinteraction',
    },
    {
        exportedFigmaName: 'vistabet-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-vistabet',
        name: 'Vistabet',
    },
    {
        exportedFigmaName: 'wheeloffortune-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-wheel-of-fortune',
        name: 'Wheeloffortune',
    },
    {
        exportedFigmaName: 'whitelabel-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-whitelabel',
        name: 'Whitelabel',
    },
    {
        exportedFigmaName: 'betmgm-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-mgm-4-light',
        name: 'BetMGM-light (not used yet)',
    },
    {
        exportedFigmaName: 'betmgm-dark',
        enableDarkBg: true,
        mainThemeparkClass: 'th-mgm-4-dark',
        name: 'BetMGM-dark (not used yet)',
    },
    {
        exportedFigmaName: 'borgata-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-borgata-2-light',
        name: 'Borgata-light (not used yet)',
    },
    {
        exportedFigmaName: 'borgata-dark',
        enableDarkBg: true,
        mainThemeparkClass: 'th-borgata-2-dark',
        name: 'Borgata-dark (not used yet)',
    },
    {
        exportedFigmaName: 'betcity-light',
        enableDarkBg: false,
        mainThemeparkClass: 'th-betcity',
        name: 'BetCity-light (On Hold)',
    },
];
