export const SplitScreenConfig = {
    fullAndQuad: {
        options: {
            splitScreenTemplatesInitialRunner: 12,
        },
        runners: [
            {
                runnerNumber: 12,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 6,
                        totalRunners: 6,
                        templateClass: 'rcTemplate6',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 7,
                        EndPageIndex: 12,
                        totalRunners: 6,
                        templateClass: 'rcTemplate6',
                    },
                ],
            },
            {
                runnerNumber: 13,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 6,
                        totalRunners: 6,
                        templateClass: 'rcTemplate6',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 7,
                        EndPageIndex: 13,
                        totalRunners: 8,
                        templateClass: '',
                    },
                ],
            },
            {
                runnerNumber: 14,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 6,
                        totalRunners: 6,
                        templateClass: 'rcTemplate6',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 7,
                        EndPageIndex: 14,
                        totalRunners: 8,
                        templateClass: '',
                    },
                ],
            },
            {
                runnerNumber: 15,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 15,
                        totalRunners: 8,
                        templateClass: '',
                    },
                ],
            },
            {
                runnerNumber: 16,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: '',
                    },
                ],
            },
            {
                runnerNumber: 17,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 17,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 18,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 18,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 19,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 10,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 11,
                        EndPageIndex: 19,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 20,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 10,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 11,
                        EndPageIndex: 20,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 21,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 6,
                        totalRunners: 6,
                        templateClass: 'rcTemplate6',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 7,
                        EndPageIndex: 14,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 15,
                        EndPageIndex: 21,
                        totalRunners: 8,
                        templateClass: '',
                    },
                ],
            },
            {
                runnerNumber: 22,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 6,
                        totalRunners: 6,
                        templateClass: 'rcTemplate6',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 7,
                        EndPageIndex: 14,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 15,
                        EndPageIndex: 22,
                        totalRunners: 8,
                        templateClass: '',
                    },
                ],
            },
            {
                runnerNumber: 23,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 17,
                        EndPageIndex: 23,
                        totalRunners: 8,
                        templateClass: '',
                    },
                ],
            },
            {
                runnerNumber: 24,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 17,
                        EndPageIndex: 24,
                        totalRunners: 8,
                        templateClass: '',
                    },
                ],
            },
            {
                runnerNumber: 25,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 17,
                        EndPageIndex: 25,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 26,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 18,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 19,
                        EndPageIndex: 26,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 27,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 18,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 19,
                        EndPageIndex: 27,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 28,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: '',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 18,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 19,
                        EndPageIndex: 28,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 29,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 10,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 11,
                        EndPageIndex: 20,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 21,
                        EndPageIndex: 29,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 30,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 10,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 11,
                        EndPageIndex: 20,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 21,
                        EndPageIndex: 30,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 31,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 17,
                        EndPageIndex: 24,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 4,
                        StartPageIndex: 25,
                        EndPageIndex: 31,
                        totalRunners: 6,
                        templateClass: 'rcTemplate8',
                    },
                ],
            },
            {
                runnerNumber: 32,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 17,
                        EndPageIndex: 24,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 4,
                        StartPageIndex: 25,
                        EndPageIndex: 32,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                ],
            },
            {
                runnerNumber: 33,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 17,
                        EndPageIndex: 24,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 4,
                        StartPageIndex: 25,
                        EndPageIndex: 33,
                        totalRunners: 8,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 34,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 17,
                        EndPageIndex: 24,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 4,
                        StartPageIndex: 25,
                        EndPageIndex: 34,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 35,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 17,
                        EndPageIndex: 24,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 4,
                        StartPageIndex: 25,
                        EndPageIndex: 35,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 36,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 17,
                        EndPageIndex: 26,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 4,
                        StartPageIndex: 27,
                        EndPageIndex: 36,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 37,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 17,
                        EndPageIndex: 26,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 4,
                        StartPageIndex: 27,
                        EndPageIndex: 37,
                        totalRunners: 11,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 38,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 8,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 9,
                        EndPageIndex: 16,
                        totalRunners: 8,
                        templateClass: 'rcTemplate8',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 17,
                        EndPageIndex: 26,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 4,
                        StartPageIndex: 27,
                        EndPageIndex: 38,
                        totalRunners: 12,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 39,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 10,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 11,
                        EndPageIndex: 20,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 21,
                        EndPageIndex: 29,
                        totalRunners: 9,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 4,
                        StartPageIndex: 30,
                        EndPageIndex: 39,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
            {
                runnerNumber: 40,
                pages: [
                    {
                        pageNumber: 1,
                        StartPageIndex: 1,
                        EndPageIndex: 10,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 2,
                        StartPageIndex: 11,
                        EndPageIndex: 20,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 3,
                        StartPageIndex: 21,
                        EndPageIndex: 30,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                    {
                        pageNumber: 4,
                        StartPageIndex: 31,
                        EndPageIndex: 40,
                        totalRunners: 10,
                        templateClass: 'rcTemplate10',
                    },
                ],
            },
        ],
    },
};
